apiVersion: v1
kind: Secret
metadata:
  name: mongodb
  labels:
    app.kubernetes.io/component: mongodb
    {{- include "ratings.labels" . | nindent 4 }}
type: Opaque
data:
  ratings_mongo_url: {{ .Values.ratingsMongoUrl | b64enc }}